- .adr-dir
- README.md
- docs/architecture/decisions/0001-record-architecture-decisions.md
> feat: modified README

- .travis.yml
> Add travis specs

- README.md
- docs/architecture/decisions/0004-log-messages.md
- fare/grant_staff/api.py
PR for merging the logging messages
> Feature logging

- Pipfile.lock
Resolved the error:
38076: bleach <=3.1.1 resolved (3.1.1 installed)!
> feat: updated packages

- fare/file_management/api.py
- fare/file_management/views.py
added the log functions to the api and view in the file-management module
> feat: added logging and checks in the file-management views and api

- .travis.yml
- docs/authors.rst
- fare/file_management/views.py
- tests/test_file_operations.py
- tests/test_user_permission.py
This PR partially fixes #75 
* add mkdir in Travis
> Add mkdir for tests

- fare/file_management/templates/file_management/create.html
- fare/file_management/views.py
> fix: stored the contributors properly

- Pipfile
- Pipfile.lock
This PR Fixes #105 
updated Invenio version to 3.3.0
> feat: #105 updated Pipfile to upgrade to version 3.3.0

- Pipfile.lock
This PR Fixes #issue_number
Updated the Pipfile.lock
> fix: updated the pipfile lock

- Pipfile.lock
- fare/file_management/templates/file_management/user_uploads.html
- fare/theme/assets/scss/fare/status-files.scss
This PR Fixes
fixed display issue of records in `user_upload.html` and updated the `Pipfile.lock`
> Fix ui issues

- docker-compose.fare.yml
modified web-ui lo_data volumes to store files permanently
> Modified web-ui lo_data volume

- .env.example
- .gitignore
- docker-services.yml
- docker/haproxy/Dockerfile
- docker/nginx/Dockerfile
- docker/nginx/conf.d/default.conf
Modified the nginx and haproxy Dockerfiles to make possible to insert certificates other than test ones
> Certificates strategy

- Pipfile.lock
> updated the Pipfile.lock

- Pipfile
- Pipfile.lock
Changed importlib-metadata version in Pipfile from 2.0.0 to 1.7.0
> fix: updated importlib-metadata version in Pipfile

- fare/conference/views.py
- fare/theme/templates/fare/frontpage.html
Created buttons in the frontpage
> Feature buttons frontpage

- fare/conference/forms.py
- fare/conference/views.py
Enanched validation fields in the room form
> fix: fixed fileds validity when creating and joining a room

- docs/Backup_and_restore_FARE.md
- script_restore.sh
fixed the restore script and updated the backup documentation
> fixed restore script and updated the backup documentation

- fare/conference/views.py
Added a random password for moderators when a virtual room is created. In this way the creator joins with moderator role
> feat: added moderator password when a virtual room is created

- fare/conference/templates/conference/info_create.html
- fare/conference/templates/conference/join_conference.html
- fare/file_management/templates/file_management/info_create.html
- fare/file_management/views.py
- fare/theme/assets/scss/fare/theme.scss
- fare/theme/templates/fare/frontpage.html
Added explanation for the accessibility of pages
> feat added explanation for the accessibility of pages

- Pipfile
- Pipfile.lock
- docker-compose.fare.yml
- docker-compose.full.yml
- fare/conference/templates/conference/info_create.html
- fare/config.py
- fare/file_management/templates/file_management/create.html
- fare/file_management/templates/file_management/info_create.html
- pyproject.toml
- scripts/server
This PR fixes
#219 #74 
Upgrading from Invenio v3.3 to v3.4 following [this guide](https://invenio.readthedocs.io/en/latest/releases/upgrading/upgrade-3_3-3_4.html)
> feat: upgrade to 3.4 version

- fare/conference/templates/conference/info_create.html
- fare/conference/views.py
- fare/file_management/templates/file_management/info_create.html
- fare/file_management/views.py
- fare/theme/templates/fare/frontpage.html
modified pages to inform the user if doesn't have the rights to upload a content or create a virtual room
> fix update info pages and frontpage

- fare/conference/views.py
> feat: enabled conference recording

- .env.example
- .gitignore
- fare/config.py
- fare/records/config.py
This PR fixes the way logging is configured
> Moved logging config setup in main fare config.py

- .github/workflows/tests.yml
> Test multiple runs
